### ISSUE TITLE
Canbus/CanOpen CIA402 for Odrive/SimpleFOC Arduino.

### ISSUE THREAD

**Issue by MatthewReed303** [kubabuda/ecat_servo#1]
Hi there,

I'm quite interested in your project. I'm wondering if there is a way to use the Canbus which is already built into the Odrive and then use the CIA402 stack on the Odrive or SimpleFOC. I'm currently using SimpleFOC [https://github.com/simplefoc/Arduino-FOC](url) [https://simplefoc.com/](url) on custom Odrive based hardware. The Odrive uses the STM32F405 and I see you have been using the STM32F103 (Bluepill) 

I would like to use the Odrive and SimpleFOC with Industrial software such as CodeSys and use PLC Open Motion Control. You can see my post regarding this on the CodeSys forum and posted on reddit PLC [https://forge.codesys.com/forge/talk/Motion/thread/d7a02bdcc7/](url) and [https://www.reddit.com/r/PLC/comments/p38o1s/plc_open_motion_control_axis_ref_structure_codesys/](url) Note: CodeSys supports CIA402 via CANopen and Ethercat. Similar to Beckhoff Twincat.  What are your thoughts on getting this to work with CANOpen and Arduino framework? 

Thanks,
Matthew

**Comment by kubabuda** [comment]
Hi, if you have a look at sources I have been using F407, not that it makes difference here.

What you want should not be too hard. There is a few steps to follow.
- Pick CANopen stack (application layer protocol, CAN in itself is just data link) like Canfestival,  CanOpenNode or Lely. Do your own research here, I have never used any. Get one with working Object Dictionary editor tool, doing it by hand is PITA
- Make stack work on your platform. Usually you need to implement few driver functions, like read/write CAN frame. Obviously stack specific, refer to docs for what you selected
- Make sure your slave device talks with your master software: add RXPDO and TXPDO with variable or two. See if values are flowing from master to slave with printf or breakpoint. Set RXPDO (slave to master) to millis() or some frame counter and see if value is changing on master side. 
- Document how to set up your master software and what HW is needed so I can duplicate setup 😀
- Using Object Dictionary editor implement required objects: control/status words, error register, supported drive modes, selected drive mode… if you want to control with position, also position target and position actual. You can refer to OD implementation in my project, which is fairly minimal implementation. Make sure data types (u16, u32…) and memory addresses (0x6040, 0x6041) are matching
- Make sure your slave device with updated OD can communicate with master software
- Copy CiA402 profile code from my repo and connect OD variables to profile structure. It was designed to be stack independent, you just setup pointers in your app startup. If you implement CiA402 application as loopback (position actual = target position, just as in my examples) you can now test if your dummy axis is working
- When your CiA402 device is working as dummy, you can integrate it with odrive or whatever servodrive backend you got there

You can do it all with Arduino for convinience, though not sure how much overhead will it bring over ST libs. You want your industrial comms to be as fast as possible, and CANopen is not the fastest car in town to begin with.
 CANopen profile specifications are paywalled but older versions one can google for free on some french dude page. It is only <100 pages for CiA402 and better have it at hand. 
Goodspeed.
