### ISSUE TITLE
Any PCB design example?

### ISSUE THREAD

**Issue by qiayuanl** [kubabuda/ecat_servo#2]
Hi, your document and code are awesome!
Is there any open-source PCB (schematic and/or layout) that allows me to build and test this project at hand? I only found the IBOM.

**Comment by kubabuda** [comment]
Hey, good that you like it :)
If you can find LAN9252 chips, there are a few open source projects available on Github. 
I started with this one: https://github.com/yuqlid/EtherCAT_board , I changed RJ45 magjacks to cheaper HanRun and rerouted parts. Unfortunately I probably botched something in routing, and only 1 port is working on that PCB.
There is also this one https://github.com/DieBieEngineering/DieBieSlave
Or if you can just get EasyCAT board.

**Comment by qiayuanl** [comment]
Thank you for your reply.

I got a evaluate board of ax58100, and I will test your code recently.

I also can get ax58200 but I am not familiar with its development environment.

**Comment by kubabuda** [comment]
You did good starting with evalboard to start with. If something is not working you can trust problem is in your code, not bad DIY rev1 hardware or hand soldering.
I got spare blank AX58100 PCBs left for that ibom project, if you want a few

I also have seen AX58200 eval boards. Seems like cool part, but I have not seen bare AX58200 chips available anywhere for building application design. If chips are available, they are ARM M4 so setting up toolchain should not be too bad

**Comment by qiayuanl** [comment]
Actually, I can get an AX58200 at 10$ per piece in China, but there is an M480 from nuvoton inside with fewer development resources.

I am trying to develop a FOC driver based on the TMC4671 for the legged robot with an EtherCAT interface. In fact, I am still struggling to develop based on your project or trying to learn to develop on AX58200. The latter is obviously more elegant, considering that the TMC4671 already takes care of all the FOC calculations we only need MCU for commutation. But I am only familiar with using CubeMX + gcc-arm + CLion/makefile + openocd or platform io.

**Comment by kubabuda** [comment]
Where can you buy AX58200? I have seen offer on Taobao, but as far as I understand lead time is six months.

If can reasonably get these, I'll try to make it work with platformio. OpenNuvoton BSP for M480 is published on github.

**Comment by qiayuanl** [comment]
> Where can you buy AX58200? I have seen offer on Taobao, but as far as I understand lead time is six months.
> 
> If can reasonably get these, I'll try to make it work with platformio. OpenNuvoton BSP for M480 is published on github.

I will send a private email to you.

**Comment by qiayuanl** [comment]
> > Where can you buy AX58200? I have seen offer on Taobao, but as far as I understand lead time is six months.
> > 
> > If can reasonably get these, I'll try to make it work with platformio. OpenNuvoton BSP for M480 is published on github.
> 
> I will send a private email to you.

Well, I can't find your email address.

I buy the AX58200 from  [this shop](https://m.tb.cn/h.fsxMzHt). You can get the single chip AX58200 at a quite low prices ($10.31) once you brought an evaluation board provided by them.

Please let me know if you have any communication problem with the shop.

**Comment by qiayuanl** [comment]
My email is liaoqiayuan@gmail.com, please feel free to contact me if you have any questions.
