### ISSUE TITLE
how to use

### ISSUE THREAD

**Issue by zouzhe1** [kubabuda/ecat_servo#3]

**Comment by zouzhe1** [comment]
slave is not important,      master is very  important

**Comment by kubabuda** [comment]
You can use:
- TwinCAT (demo/dev license, or buy soft PLC license for production usage)
- LinuxCNC with EtherCAT integration https://github.com/sittner/linuxcnc-ethercat
- write CiA402 master yourself (or copy from @sittner ) and use it with SOES or IgH EtherCAT master
