### ISSUE TITLE
Missing ESC hardware

### ISSUE THREAD

**Issue by Shep-pard** [kubabuda/ecat_servo#8]
Hey kubabuda, 
sorry this isn't an issue but I couldn't find another way of messaging you. 
I've read in your docs you've put your testing with the stmbl on hold for the time being due to the hw unavailability. 

Some time ago I had the same issue and redesigned the stmbl with another driver IC to be able to build some:
https://github.com/Shep-pard/stmbl

The layout could be improved I had some issues with the current monitoring (its pretty noisy but mostly works) 
I have at least one left over which I don't need if you want some hardware to experiment with.

**Comment by kubabuda** [comment]
Hi, unavailable HW I was writing about was probably ESC (EtherCAT chips). At the moment all the ESCs are back in stock (AX58100 and LAN9253 that has Beckhoff mode and will work with my AX58100 code). 
I have handful finished v4.3 STMBL boards, enough for tests. I got STMBL addon designed, few boards assembled, now limiting factor is time for firmware work and test.

I got few questions to your layout but it is forked repo and has issues tab disabled. Can you enable it, or what is your email/some other way to talk with you?

**Comment by Shep-pard** [comment]
Oh ok didn‘t know they also had a shortage 
But then you were Lucky you still got some IRAMs :)


I’ve enabled the issues, but you can also email me:
![IMG_2274](https://github.com/kubabuda/ecat_servo/assets/10660121/4520d662-25c9-46df-b9fc-9a54f7ab9238)
