### ISSUE TITLE
Plan for FoE

### ISSUE THREAD

**Issue by qiayuanl** [kubabuda/ecat_servo#9]
Hello! Your project is truly impressive! Thanks to your project, I've successfully built FOC motor drivers and IMU EtherCAT slaves using AX58100 and AX58400. Additionally, I've managed to operate up to 20 slaves at 1kHz with SOEM. I'm considering open-sourcing the code in the future.

However, updating the firmware on these slaves when installed in a robot is quite challenging. Do you have any plans to include a tutorial for File over EtherCAT (FoE)?

**Comment by kubabuda** [comment]
Hello,
Making FoE work is definitely on my todo list, but I have very limited time for this nowadays

**Comment by qiayuanl** [comment]
I successfully run FoE write with the SOEM example. Maybe try FoE read someday for calibration and log reading.
